blank_issues_enabled: true
contact_links:
  - name: Documentation 📃
    url: https://sciencedata.dk/sites/sciencerepository/
    about: Questions regarding Zenodo? Take a look at our FAQs
  - name: Developer documentation 💻
    url: https://sciencedata.dk/sites/sciencerepository/api
    about: Other type of issue? Ask for support
  - name: Support questions 💬
    url: https://sciencerepository.dk/support
    about: Other type of issue? Ask for support
